userdel -r de_junious 
userdel -r nunez_gomez 
userdel -r uellaegoess 
userdel -r lanpher 
userdel -r galvin 
userdel -r laspina 
userdel -r dodich 
userdel -r bannowsky 
userdel -r waisath 
userdel -r von_reddig-piette 
userdel -r latona 
userdel -r homewood 
userdel -r pallafor-zedian 
userdel -r senemounnarat-quillian 
userdel -r isaac 
userdel -r plancarte 
userdel -r berteotti-stirn 
userdel -r strycker 
userdel -r von_verrill 
userdel -r deschner 
userdel -r franzi 
userdel -r cringle 
userdel -r kosh 
userdel -r derouchie 
userdel -r doutt 
userdel -r munley 
userdel -r dornbos 
userdel -r mahala 
userdel -r ellingwood 
userdel -r de_cardinalli-sciola 
userdel -r gundry 
userdel -r pinedo 
userdel -r pinsky 
userdel -r pinsky1 
userdel -r pinsky2 
userdel -r pinsky3 
