useradd  -d /home/klassen -c 1am -m  -g 1am -G cdrom,plugdev,sambashare -s /bin/bash 1am
useradd  -d /home/klassen -c 1bm -m  -g 1bm -G cdrom,plugdev,sambashare -s /bin/bash 1bm
useradd  -d /home/klassen -c 1cm -m  -g 1cm -G cdrom,plugdev,sambashare -s /bin/bash 1cm
useradd  -d /home/klassen -c 2am -m  -g 2am -G cdrom,plugdev,sambashare -s /bin/bash 2am
useradd  -d /home/klassen -c 2bm -m  -g 2bm -G cdrom,plugdev,sambashare -s /bin/bash 2bm
useradd  -d /home/klassen -c 2cm -m  -g 2cm -G cdrom,plugdev,sambashare -s /bin/bash 2cm
useradd  -d /home/klassen -c 3am -m  -g 3am -G cdrom,plugdev,sambashare -s /bin/bash 3am
useradd  -d /home/klassen -c 3bm -m  -g 3bm -G cdrom,plugdev,sambashare -s /bin/bash 3bm
useradd  -d /home/klassen -c 3cm -m  -g 3cm -G cdrom,plugdev,sambashare -s /bin/bash 3cm
useradd  -d /home/klassen -c 4am -m  -g 4am -G cdrom,plugdev,sambashare -s /bin/bash 4am
useradd  -d /home/klassen -c 4bm -m  -g 4bm -G cdrom,plugdev,sambashare -s /bin/bash 4bm
useradd  -d /home/klassen -c 4cm -m  -g 4cm -G cdrom,plugdev,sambashare -s /bin/bash 4cm
useradd  -d /home/klassen -c 5am -m  -g 5am -G cdrom,plugdev,sambashare -s /bin/bash 5am
useradd  -d /home/klassen -c 5bm -m  -g 5bm -G cdrom,plugdev,sambashare -s /bin/bash 5bm
useradd  -d /home/klassen -c 5cm -m  -g 5cm -G cdrom,plugdev,sambashare -s /bin/bash 5cm
useradd  -d /home/klassen -c 1af -m  -g 1af -G cdrom,plugdev,sambashare -s /bin/bash 1af
useradd  -d /home/klassen -c 1bf -m  -g 1bf -G cdrom,plugdev,sambashare -s /bin/bash 1bf
useradd  -d /home/klassen -c 1cf -m  -g 1cf -G cdrom,plugdev,sambashare -s /bin/bash 1cf
useradd  -d /home/klassen -c 2af -m  -g 2af -G cdrom,plugdev,sambashare -s /bin/bash 2af
useradd  -d /home/klassen -c 2bf -m  -g 2bf -G cdrom,plugdev,sambashare -s /bin/bash 2bf
useradd  -d /home/klassen -c 3afi -m  -g 3afi -G cdrom,plugdev,sambashare -s /bin/bash 3afi
useradd  -d /home/klassen -c 3bfn -m  -g 3bfn -G cdrom,plugdev,sambashare -s /bin/bash 3bfn
useradd  -d /home/klassen -c 4afi -m  -g 4afi -G cdrom,plugdev,sambashare -s /bin/bash 4afi
useradd  -d /home/klassen -c 4bfn -m  -g 4bfn -G cdrom,plugdev,sambashare -s /bin/bash 4bfn
useradd  -d /home/klassen -c 1ai -m  -g 1ai -G cdrom,plugdev,sambashare -s /bin/bash 1ai
useradd  -d /home/klassen -c 1bi -m  -g 1bi -G cdrom,plugdev,sambashare -s /bin/bash 1bi
useradd  -d /home/klassen -c 1ci -m  -g 1ci -G cdrom,plugdev,sambashare -s /bin/bash 1ci
useradd  -d /home/klassen -c 2ai -m  -g 2ai -G cdrom,plugdev,sambashare -s /bin/bash 2ai
useradd  -d /home/klassen -c 2bi -m  -g 2bi -G cdrom,plugdev,sambashare -s /bin/bash 2bi
useradd  -d /home/klassen -c 2ci -m  -g 2ci -G cdrom,plugdev,sambashare -s /bin/bash 2ci
useradd  -d /home/klassen -c 3ai -m  -g 3ai -G cdrom,plugdev,sambashare -s /bin/bash 3ai
useradd  -d /home/klassen -c 3bi -m  -g 3bi -G cdrom,plugdev,sambashare -s /bin/bash 3bi
useradd  -d /home/klassen -c 3ci -m  -g 3ci -G cdrom,plugdev,sambashare -s /bin/bash 3ci
useradd  -d /home/klassen -c 4ai -m  -g 4ai -G cdrom,plugdev,sambashare -s /bin/bash 4ai
useradd  -d /home/klassen -c 4bi -m  -g 4bi -G cdrom,plugdev,sambashare -s /bin/bash 4bi
useradd  -d /home/klassen -c 4cn -m  -g 4cn -G cdrom,plugdev,sambashare -s /bin/bash 4cn
useradd  -d /home/klassen -c 5ax -m  -g 5ax -G cdrom,plugdev,sambashare -s /bin/bash 5ax
useradd  -d /home/klassen -c 5bi -m  -g 5bi -G cdrom,plugdev,sambashare -s /bin/bash 5bi
useradd  -d /home/klassen -c 5cn -m  -g 5cn -G cdrom,plugdev,sambashare -s /bin/bash 5cn
useradd  -d /home/klassen -c 1ao -m  -g 1ao -G cdrom,plugdev,sambashare -s /bin/bash 1ao
