useradd  -d /home/klassen/k1am -c k1am -m  -g k1am -G cdrom,plugdev,sambashare -s /bin/bash k1am
useradd  -d /home/klassen/k1bm -c k1bm -m  -g k1bm -G cdrom,plugdev,sambashare -s /bin/bash k1bm
useradd  -d /home/klassen/k1cm -c k1cm -m  -g k1cm -G cdrom,plugdev,sambashare -s /bin/bash k1cm
useradd  -d /home/klassen/k2am -c k2am -m  -g k2am -G cdrom,plugdev,sambashare -s /bin/bash k2am
useradd  -d /home/klassen/k2bm -c k2bm -m  -g k2bm -G cdrom,plugdev,sambashare -s /bin/bash k2bm
useradd  -d /home/klassen/k2cm -c k2cm -m  -g k2cm -G cdrom,plugdev,sambashare -s /bin/bash k2cm
useradd  -d /home/klassen/k3am -c k3am -m  -g k3am -G cdrom,plugdev,sambashare -s /bin/bash k3am
useradd  -d /home/klassen/k3bm -c k3bm -m  -g k3bm -G cdrom,plugdev,sambashare -s /bin/bash k3bm
useradd  -d /home/klassen/k3cm -c k3cm -m  -g k3cm -G cdrom,plugdev,sambashare -s /bin/bash k3cm
useradd  -d /home/klassen/k4am -c k4am -m  -g k4am -G cdrom,plugdev,sambashare -s /bin/bash k4am
useradd  -d /home/klassen/k4bm -c k4bm -m  -g k4bm -G cdrom,plugdev,sambashare -s /bin/bash k4bm
useradd  -d /home/klassen/k4cm -c k4cm -m  -g k4cm -G cdrom,plugdev,sambashare -s /bin/bash k4cm
useradd  -d /home/klassen/k5am -c k5am -m  -g k5am -G cdrom,plugdev,sambashare -s /bin/bash k5am
useradd  -d /home/klassen/k5bm -c k5bm -m  -g k5bm -G cdrom,plugdev,sambashare -s /bin/bash k5bm
useradd  -d /home/klassen/k5cm -c k5cm -m  -g k5cm -G cdrom,plugdev,sambashare -s /bin/bash k5cm
useradd  -d /home/klassen/k1af -c k1af -m  -g k1af -G cdrom,plugdev,sambashare -s /bin/bash k1af
useradd  -d /home/klassen/k1bf -c k1bf -m  -g k1bf -G cdrom,plugdev,sambashare -s /bin/bash k1bf
useradd  -d /home/klassen/k1cf -c k1cf -m  -g k1cf -G cdrom,plugdev,sambashare -s /bin/bash k1cf
useradd  -d /home/klassen/k2af -c k2af -m  -g k2af -G cdrom,plugdev,sambashare -s /bin/bash k2af
useradd  -d /home/klassen/k2bf -c k2bf -m  -g k2bf -G cdrom,plugdev,sambashare -s /bin/bash k2bf
useradd  -d /home/klassen/k3afi -c k3afi -m  -g k3afi -G cdrom,plugdev,sambashare -s /bin/bash k3afi
useradd  -d /home/klassen/k3bfn -c k3bfn -m  -g k3bfn -G cdrom,plugdev,sambashare -s /bin/bash k3bfn
useradd  -d /home/klassen/k4afi -c k4afi -m  -g k4afi -G cdrom,plugdev,sambashare -s /bin/bash k4afi
useradd  -d /home/klassen/k4bfn -c k4bfn -m  -g k4bfn -G cdrom,plugdev,sambashare -s /bin/bash k4bfn
useradd  -d /home/klassen/k1ai -c k1ai -m  -g k1ai -G cdrom,plugdev,sambashare -s /bin/bash k1ai
useradd  -d /home/klassen/k1bi -c k1bi -m  -g k1bi -G cdrom,plugdev,sambashare -s /bin/bash k1bi
useradd  -d /home/klassen/k1ci -c k1ci -m  -g k1ci -G cdrom,plugdev,sambashare -s /bin/bash k1ci
useradd  -d /home/klassen/k2ai -c k2ai -m  -g k2ai -G cdrom,plugdev,sambashare -s /bin/bash k2ai
useradd  -d /home/klassen/k2bi -c k2bi -m  -g k2bi -G cdrom,plugdev,sambashare -s /bin/bash k2bi
useradd  -d /home/klassen/k2ci -c k2ci -m  -g k2ci -G cdrom,plugdev,sambashare -s /bin/bash k2ci
useradd  -d /home/klassen/k3ai -c k3ai -m  -g k3ai -G cdrom,plugdev,sambashare -s /bin/bash k3ai
useradd  -d /home/klassen/k3bi -c k3bi -m  -g k3bi -G cdrom,plugdev,sambashare -s /bin/bash k3bi
useradd  -d /home/klassen/k3ci -c k3ci -m  -g k3ci -G cdrom,plugdev,sambashare -s /bin/bash k3ci
useradd  -d /home/klassen/k4ai -c k4ai -m  -g k4ai -G cdrom,plugdev,sambashare -s /bin/bash k4ai
useradd  -d /home/klassen/k4bi -c k4bi -m  -g k4bi -G cdrom,plugdev,sambashare -s /bin/bash k4bi
useradd  -d /home/klassen/k4cn -c k4cn -m  -g k4cn -G cdrom,plugdev,sambashare -s /bin/bash k4cn
useradd  -d /home/klassen/k5ax -c k5ax -m  -g k5ax -G cdrom,plugdev,sambashare -s /bin/bash k5ax
useradd  -d /home/klassen/k5bi -c k5bi -m  -g k5bi -G cdrom,plugdev,sambashare -s /bin/bash k5bi
useradd  -d /home/klassen/k5cn -c k5cn -m  -g k5cn -G cdrom,plugdev,sambashare -s /bin/bash k5cn
useradd  -d /home/klassen/k1ao -c k1ao -m  -g k1ao -G cdrom,plugdev,sambashare -s /bin/bash k1ao
useradd  -d /home/lehrer -c lehrer -m  -g lehrer -G cdrom,plugdev,sambashare -s /bin/bash lehrer
useradd  -d /home/lehrer -c seminar -m  -g seminar -G cdrom,plugdev,sambashare -s /bin/bash seminar
